### PR TITLE
code folding

### PR DESCRIPTION
**Pull request by jasonnn**
This is pretty rough but it seems to work alright.

### CODE REVIEW

**Comment by parrt** [comment]
Hi.  I will look at this as soon as I get a chance. Thank you!  Did you add yourself to the contributors.txt file?

**Comment by parrt** [comment]
actually, this will mess up. can you fork from https://github.com/antlr/intellij-plugin-v4 and resubmit remaining three?

**Comment by jasonnn** [comment]
wow i was really out of date.

**Comment by parrt** [comment]
ha! I hadn't work in parrt fork for a bit apparently!

**Comment by parrt** [comment]
can you give me a quick contributors.txt update? I have merged your old w/o it.

**Pull request closed without merging**
